name: NCCABoilerplate

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        platform: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Run vcpkg
      uses: lukka/run-vcpkg@v4
      with:
       vcpkgJsonGlob: '**/vcpkg.json'

    - name: Configure
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_TOOLCHAIN_FILE=~/vcpkg/scripts/buildsystems/vcpkg.cmake  -DVCPKG_MANIFEST_DIR=../manifest/ .. 
               
    - name: Build
      run: |
        cd build
        cmake --build . 
    - name: Test
      run: |
        build/GTest/GTestBoilerPlate
